#!/usr/bin/env bash
# Shipyard installer — Compose stack + Bun UI + Caddy (preferred) or nginx config.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

YES=0
PROXY="${PROXY:-caddy}"
DOMAIN="${DOMAIN:-localhost}"
EMAIL="${EMAIL:-}"
PUBLIC_URL="${PUBLIC_URL:-}"
SKIP_UI="${SKIP_UI:-0}"
SKIP_COMPOSE="${SKIP_COMPOSE:-0}"

for arg in "$@"; do
  case "$arg" in
    --yes|-y) YES=1 ;;
    --proxy=*) PROXY="${arg#*=}" ;;
    --domain=*) DOMAIN="${arg#*=}" ;;
    --skip-ui) SKIP_UI=1 ;;
    --skip-compose) SKIP_COMPOSE=1 ;;
    --help|-h)
      cat <<'EOF'
Usage: ./scripts/install.sh [--yes] [--proxy=caddy|nginx|none] [--domain=host] [--skip-ui] [--skip-compose]

Environment:
  DOMAIN          Public hostname (default: localhost)
  EMAIL           ACME email for Caddy (optional)
  PROXY           caddy | nginx | none (default: caddy)
  PUBLIC_URL      Override SHIPYARD_PUBLIC_URL
  SKIP_UI=1       Do not bun install / start UI
  SKIP_COMPOSE=1  Do not start Docker Compose
EOF
      exit 0
      ;;
  esac
done

log() { printf '==> %s\n' "$*"; }
warn() { printf '!!  %s\n' "$*" >&2; }
die() { warn "$*"; exit 1; }

prompt() {
  local var="$1" msg="$2" def="${3:-}"
  if [[ "$YES" -eq 1 ]]; then
    printf -v "$var" '%s' "${!var:-$def}"
    return
  fi
  local cur="${!var:-$def}"
  read -r -p "$msg [$cur]: " ans || true
  if [[ -n "${ans:-}" ]]; then
    printf -v "$var" '%s' "$ans"
  else
    printf -v "$var" '%s' "$cur"
  fi
}

have() { command -v "$1" >/dev/null 2>&1; }

setup_docker_env() {
  if [[ -S "/run/user/$(id -u)/docker.sock" ]]; then
    export DOCKER_HOST="unix:///run/user/$(id -u)/docker.sock"
    export PATH="${HOME}/bin:${PATH}"
    log "Using rootless Docker socket"
  fi
  have docker || die "Docker not found. Install Docker Engine or rootless Docker."
  docker info >/dev/null 2>&1 || die "Cannot talk to Docker daemon (docker info failed)."
}

rand_b64_32() {
  if have openssl; then
    openssl rand -base64 32 | tr -d '\n'
  else
    head -c 32 /dev/urandom | base64 | tr -d '\n'
  fi
}

write_env() {
  if [[ -f .env ]]; then
    log ".env already exists — keeping it"
    return
  fi
  log "Writing .env"
  local secrets webhook
  secrets="$(rand_b64_32)"
  webhook="$(rand_b64_32)"
  if [[ -z "$PUBLIC_URL" ]]; then
    if [[ "$DOMAIN" == "localhost" || "$DOMAIN" == "127.0.0.1" ]]; then
      PUBLIC_URL="http://127.0.0.1:5173"
    else
      PUBLIC_URL="https://${DOMAIN}"
    fi
  fi
  cat > .env <<EOF
SHIPYARD_HTTP_ADDR=:8080
SHIPYARD_DATABASE_URL=postgres://shipyard:shipyard@localhost:5432/shipyard?sslmode=disable
SHIPYARD_MIGRATIONS_DIR=migrations
SHIPYARD_STORAGE_BACKEND=filesystem
SHIPYARD_STORAGE_DIR=data/blobs
SHIPYARD_LOG_LEVEL=info
SHIPYARD_ALLOW_REGISTER=true
SHIPYARD_SESSION_TTL=168h
SHIPYARD_PUBLIC_URL=${PUBLIC_URL}
SHIPYARD_SECRETS_KEY=${secrets}
SHIPYARD_WEBHOOK_SECRET=${webhook}
SHIPYARD_DOMAIN=${DOMAIN}
EOF
  log "Generated SHIPYARD_SECRETS_KEY and SHIPYARD_WEBHOOK_SECRET"
}

start_compose() {
  [[ "$SKIP_COMPOSE" -eq 1 ]] && { log "Skipping Compose"; return; }
  log "Starting Compose stack"
  docker compose --env-file "$ROOT/.env" -f deploy/compose/compose.yml up --build -d
  log "Waiting for API healthz"
  local i
  for i in $(seq 1 60); do
    if curl -sf http://127.0.0.1:8080/healthz >/dev/null; then
      log "API is healthy"
      return
    fi
    sleep 1
  done
  die "API did not become healthy on :8080"
}

write_proxy_config() {
  case "$PROXY" in
    caddy)
      log "Writing deploy/caddy/Caddyfile.local for domain=${DOMAIN}"
      cat > deploy/caddy/Caddyfile.local <<EOF
# Generated by scripts/install.sh — domain=${DOMAIN}
${DOMAIN} {
	encode gzip zstd
	handle /api/* { reverse_proxy 127.0.0.1:8080 }
	handle /v2* { reverse_proxy 127.0.0.1:8080 }
	handle /auth/* { reverse_proxy 127.0.0.1:8080 }
	handle /repository/* { reverse_proxy 127.0.0.1:8080 }
	handle /healthz { reverse_proxy 127.0.0.1:8080 }
	handle /readyz { reverse_proxy 127.0.0.1:8080 }
	handle { reverse_proxy 127.0.0.1:5173 }
}
EOF
      if have caddy; then
        log "Caddy binary found. Example: caddy run --config ${ROOT}/deploy/caddy/Caddyfile.local"
      else
        warn "Caddy not installed. Install from https://caddyserver.com/docs/install then:"
        warn "  caddy run --config ${ROOT}/deploy/caddy/Caddyfile.local"
      fi
      ;;
    nginx)
      log "Refreshing deploy/nginx/shipyard.conf server_name=${DOMAIN}"
      sed -i.bak "s/server_name .*/server_name ${DOMAIN};/" deploy/nginx/shipyard.conf || true
      warn "Install config: sudo cp deploy/nginx/shipyard.conf /etc/nginx/sites-available/shipyard"
      warn "Enable + reload nginx, then obtain TLS (certbot) if needed."
      ;;
    none)
      log "Skipping reverse proxy config"
      ;;
    *)
      die "Unknown PROXY=$PROXY (use caddy|nginx|none)"
      ;;
  esac
}

setup_ui() {
  [[ "$SKIP_UI" -eq 1 ]] && { log "Skipping UI"; return; }
  if ! have bun; then
    warn "Bun not found — installing to ~/.bun"
    curl -fsSL https://bun.sh/install | bash
    export BUN_INSTALL="${HOME}/.bun"
    export PATH="${BUN_INSTALL}/bin:${PATH}"
  fi
  log "Installing JS workspaces"
  bun install
  log "UI typecheck"
  bun run typecheck
}

main() {
  log "Shipyard installer"
  prompt DOMAIN "Public domain" "$DOMAIN"
  prompt PROXY "Reverse proxy (caddy|nginx|none)" "$PROXY"
  if [[ "$PROXY" == "caddy" && "$DOMAIN" != "localhost" && "$DOMAIN" != "127.0.0.1" ]]; then
    prompt EMAIL "ACME email for Caddy (optional)" "${EMAIL:-}"
  fi

  setup_docker_env
  write_env
  start_compose
  write_proxy_config
  setup_ui

  cat <<EOF

────────────────────────────────────────
Shipyard is ready (local pieces).

  API:     http://127.0.0.1:8080/healthz
  UI:      bun run dev   → http://127.0.0.1:5173
  Docs:    docs/DEPLOY.md
  Proxy:   deploy/${PROXY}/

Next:
  1. bun run dev
  2. Open the UI and create the first account
  3. Settings → Integrations / Notifications (Discord)
  4. Runners → registration token → start a runner

EOF
}

main
