#!/bin/sh
set -eu
(set -o pipefail) 2>/dev/null && set -o pipefail

URL="${SHIPYARD_URL:-http://127.0.0.1:8088}"
DEMO_USER="${DEMO_USER:-demo}"
DEMO_PASSWORD="${DEMO_PASSWORD:-demo1234}"
DEMO_ORG="${DEMO_ORG:-acme}"
TOKEN_FILE="${TOKEN_FILE:-/shared/reg-token}"

COOKIE="$(mktemp)"
trap 'rm -f "$COOKIE"' EXIT

log() { printf '==> %s\n' "$*"; }

post() { curl -fsS -b "$COOKIE" -c "$COOKIE" -H 'Content-Type: application/json' -d "$2" "$URL$1"; }
get() { curl -fsS -b "$COOKIE" -c "$COOKIE" "$URL$1"; }
upload() { curl -fsS -b "$COOKIE" -c "$COOKIE" -H "Content-Type: $3" --data-binary "$2" "$URL$1"; }

log "waiting for $URL"
tries=0
until curl -fsS "$URL/readyz" >/dev/null 2>&1; do
	tries=$((tries + 1))
	if [ "$tries" -gt 150 ]; then
		echo "server never became ready at $URL" >&2
		exit 1
	fi
	sleep 2
done

log "signing in as $DEMO_USER"
creds=$(jq -n --arg u "$DEMO_USER" --arg p "$DEMO_PASSWORD" \
	'{username:$u, email:($u + "@example.com"), display_name:"Demo User", password:$p}')
post /api/v1/auth/register "$creds" >/dev/null 2>&1 ||
	post /api/v1/auth/login "$(jq -n --arg u "$DEMO_USER" --arg p "$DEMO_PASSWORD" '{login:$u, password:$p}')" >/dev/null

if existing=$(get "/api/v1/orgs/$DEMO_ORG" 2>/dev/null); then
	ORG=$(printf '%s' "$existing" | jq -r .organization.id)
	seeded=yes
else
	log "creating organization $DEMO_ORG"
	ORG=$(post /api/v1/orgs "$(jq -n --arg s "$DEMO_ORG" \
		'{slug:$s, name:"Acme Corp", description:"Demo organization — everything here is generated by scripts/seed-demo.sh"}')" |
		jq -r .organization.id)
	seeded=no
fi

log "minting a runner registration token"
mkdir -p "$(dirname "$TOKEN_FILE")"
post /api/v1/runners/registration-tokens "$(jq -n --arg o "$ORG" '{organization_id:$o, ttl:"24h"}')" |
	jq -r .token >"$TOKEN_FILE"

if [ "$seeded" = yes ]; then
	log "organization $DEMO_ORG already exists, nothing to seed"
	exit 0
fi

project() {
	post "/api/v1/orgs/$ORG/projects" "$(jq -n --arg s "$1" --arg n "$2" --arg d "$3" \
		'{slug:$s, name:$n, description:$d}')" | jq -r .project.id
}

pipeline() {
	post "/api/v1/orgs/$ORG/projects/$1/pipelines" "$(jq -n --arg s "$2" --arg y "$3" '{slug:$s, yaml:$y}')" |
		jq -r .pipeline.id
}

run() {
	post "/api/v1/orgs/$ORG/projects/$1/pipelines/$2/runs" \
		"$(jq -n --arg r "$3" --arg c "$4" '{git_ref:$r, git_sha:$c}')" | jq -r .run.id
}

log "creating projects"
CHECKOUT=$(project checkout-api "Checkout API" "Payments and cart service")
STOREFRONT=$(project web-storefront "Web Storefront" "Customer-facing React app")
GATEWAY=$(project mobile-gateway "Mobile Gateway" "GraphQL edge for the mobile clients")

CI_YAML=$(
	cat <<'YAML'
pipeline:
  name: ci

on:
  push:
    branches: [main]

jobs:
  lint:
    runner:
      os: linux
    steps:
      - name: environment
        run: |
          echo "runner   $(uname -s) $(uname -m)"
          echo "workdir  $(pwd)"
          echo "started  $(date -u +%H:%M:%SZ)"
      - name: vet sources
        run: |
          mkdir -p src
          for pkg in cart pricing tax checkout inventory shipping; do
            printf 'package %s\n' "$pkg" > "src/$pkg.go"
          done
          for f in src/*.go; do
            echo "  vet $f"
          done
          echo "scanned $(ls src | wc -l) files, 0 findings"

  test:
    runner:
      os: linux
    steps:
      - name: unit tests
        run: |
          for pkg in cart pricing tax checkout inventory shipping webhooks ledger; do
            printf 'ok\tcheckout/%s\n' "$pkg"
          done
          echo
          echo "8 packages, 0 failures"
      - name: coverage
        run: |
          echo "statements covered  1842 / 2107"
          echo "coverage            87.4%"

  build:
    needs: [lint, test]
    runner:
      os: linux
    steps:
      - name: compile
        run: |
          mkdir -p dist
          echo "target   $(uname -s | tr 'A-Z' 'a-z')/$(uname -m)"
          date -u +'checkout-api built %Y-%m-%dT%H:%M:%SZ' > dist/checkout-api
          echo "output   dist/checkout-api"
          echo "size     $(wc -c < dist/checkout-api) bytes"
      - name: checksum
        run: |
          sha256sum dist/checkout-api
          echo "ready to upload as an artifact"
YAML
)

RELEASE_YAML=$(
	cat <<'YAML'
pipeline:
  name: release

jobs:
  bundle:
    runner:
      os: linux
    steps:
      - name: build bundle
        run: |
          mkdir -p dist
          head -c 4096 /dev/urandom | base64 > dist/storefront.js
          echo "bundled dist/storefront.js ($(wc -c < dist/storefront.js) bytes)"
      - name: report size
        run: du -h dist/storefront.js

  package:
    needs: [bundle]
    runner:
      os: linux
    steps:
      - name: assemble tarball
        run: |
          mkdir -p out
          printf '{"name":"@acme/storefront","version":"2.3.1"}\n' > out/package.json
          tar -czf out/storefront-2.3.1.tgz -C out package.json
          echo "out/storefront-2.3.1.tgz ready ($(wc -c < out/storefront-2.3.1.tgz) bytes)"
YAML
)

NIGHTLY_YAML=$(
	cat <<'YAML'
pipeline:
  name: nightly

jobs:
  contract-tests:
    runner:
      os: linux
    steps:
      - name: load schemas
        run: echo "loaded 18 schema documents"
      - name: contract tests
        run: |
          echo "gateway/routes     ok"
          echo "gateway/products   ok"
          echo "gateway/cart       ok"
          echo "gateway/search     ok"
          echo "gateway/auth       FAIL"
          echo
          echo "  GET /v1/session expected 200, got 401"
          echo "  1 of 5 suites failed"
          exit 1
YAML
)

log "creating pipelines"
CI=$(pipeline "$CHECKOUT" ci "$CI_YAML")
REL=$(pipeline "$STOREFRONT" release "$RELEASE_YAML")
NIGHTLY=$(pipeline "$GATEWAY" nightly "$NIGHTLY_YAML")

log "waiting for a runner to register"
tries=0
until [ "$(get /api/v1/runners | jq '.runners | length')" -gt 0 ]; do
	tries=$((tries + 1))
	if [ "$tries" -gt 90 ]; then
		echo "no runner registered — jobs would stay queued" >&2
		exit 1
	fi
	sleep 2
done

log "starting runs"
run "$CHECKOUT" "$CI" refs/heads/main 4f1c9ab >/dev/null
run "$CHECKOUT" "$CI" refs/heads/feature/coupon-stacking 9d34e07 >/dev/null
run "$STOREFRONT" "$REL" refs/tags/v2.3.1 c07be21 >/dev/null
run "$GATEWAY" "$NIGHTLY" refs/heads/main 1ba85fd >/dev/null
BUILD_RUN=$(run "$CHECKOUT" "$CI" refs/heads/main 7e2d5c4)

log "waiting for runs to finish"
tries=0
while [ "$(get "/api/v1/orgs/$ORG/projects/$CHECKOUT/runs" | jq '[.runs[] | select(.status == "queued" or .status == "running")] | length')" -gt 0 ]; do
	tries=$((tries + 1))
	[ "$tries" -gt 120 ] && break
	sleep 2
done

log "uploading artifacts"
ART=$(date -u +'checkout-api built %Y-%m-%dT%H:%M:%SZ' |
	upload "/api/v1/orgs/$ORG/projects/$CHECKOUT/artifacts?name=checkout-api&run_id=$BUILD_RUN" @- application/octet-stream |
	jq -r .artifact.id)
printf 'coverage: 87.4%% of statements\n' |
	upload "/api/v1/orgs/$ORG/projects/$CHECKOUT/artifacts?name=coverage.txt&run_id=$BUILD_RUN" @- text/plain >/dev/null

log "creating package repositories"
NPM=$(post "/api/v1/orgs/$ORG/projects/$STOREFRONT/packages" '{"name":"web","format":"npm"}' | jq -r .repository.id)
MVN=$(post "/api/v1/orgs/$ORG/projects/$CHECKOUT/packages" '{"name":"libs","format":"maven"}' | jq -r .repository.id)

printf '{"name":"@acme/storefront","version":"2.3.1"}\n' |
	upload "/api/v1/orgs/$ORG/projects/$STOREFRONT/packages/$NPM/versions?name=@acme/storefront&version=2.3.1" @- application/octet-stream >/dev/null
printf '{"name":"@acme/storefront","version":"2.3.0"}\n' |
	upload "/api/v1/orgs/$ORG/projects/$STOREFRONT/packages/$NPM/versions?name=@acme/storefront&version=2.3.0" @- application/octet-stream >/dev/null
printf 'checkout-client 1.8.2\n' |
	upload "/api/v1/orgs/$ORG/projects/$CHECKOUT/packages/$MVN/versions?name=com.acme:checkout-client&version=1.8.2" @- application/octet-stream >/dev/null

log "pushing container image manifests"
manifest() {
	jq -n --arg d "$1" --argjson s "$2" \
		'{schemaVersion:2, mediaType:"application/vnd.oci.image.manifest.v1+json",
		  config:{mediaType:"application/vnd.oci.image.config.v1+json", digest:"sha256:b4a7c1f0e6d25839ac1b0f7e42d5c9083f6a1e2b7d4c8590fa3e6b1d0c2947fe", size:1471},
		  layers:[{mediaType:"application/vnd.oci.image.layer.v1.tar+gzip", digest:$d, size:$s}]}'
}
oci_push() {
	curl -fsS -b "$COOKIE" -c "$COOKIE" -H 'Content-Type: application/vnd.oci.image.manifest.v1+json' \
		-d "$3" "$URL/api/v1/orgs/$ORG/projects/$1/oci/checkout-api/manifests/$2" >/dev/null
}
oci_push "$CHECKOUT" 1.8.2 "$(manifest sha256:2f1d0c9b8a7e6543d21cf0b9a8e7d6c5b4a3928170f6e5d4c3b2a1908f7e6d5c 28419573)"
oci_push "$CHECKOUT" latest "$(manifest sha256:2f1d0c9b8a7e6543d21cf0b9a8e7d6c5b4a3928170f6e5d4c3b2a1908f7e6d5c 28419573)"
oci_push "$CHECKOUT" 1.8.1 "$(manifest sha256:9e8d7c6b5a4938271f0e6d5c4b3a2918f7e6d5c4b3a29180f7e6d5c4b3a29187 28402011)"

log "creating environments, releases and deployments"
STAGING=$(post "/api/v1/orgs/$ORG/projects/$CHECKOUT/environments" '{"slug":"staging","name":"Staging"}' | jq -r .environment.id)
PROD=$(post "/api/v1/orgs/$ORG/projects/$CHECKOUT/environments" '{"slug":"production","name":"Production"}' | jq -r .environment.id)

REL_1_8_2=$(post "/api/v1/orgs/$ORG/projects/$CHECKOUT/releases" "$(jq -n --arg r "$BUILD_RUN" --arg a "$ART" \
	'{version:"v1.8.2", title:"Coupon stacking", notes:"Cart totals now apply stacked coupons in a deterministic order.", run_id:$r, artifact_ids:[$a]}')" |
	jq -r .release.id)
REL_1_8_1=$(post "/api/v1/orgs/$ORG/projects/$CHECKOUT/releases" \
	'{"version":"v1.8.1","title":"Tax rounding fix","notes":"Line-item tax is rounded once at the invoice level."}' | jq -r .release.id)

post "/api/v1/orgs/$ORG/projects/$CHECKOUT/deployments" "$(jq -n --arg e "$STAGING" --arg r "$REL_1_8_2" '{environment_id:$e, release_id:$r}')" >/dev/null
post "/api/v1/orgs/$ORG/projects/$CHECKOUT/deployments" "$(jq -n --arg e "$PROD" --arg r "$REL_1_8_1" '{environment_id:$e, release_id:$r}')" >/dev/null

log "seeded $DEMO_ORG — sign in at ${DEMO_PUBLIC_URL:-$URL} with $DEMO_USER / $DEMO_PASSWORD"
